var girlSetting = {
	"right":[
	  {"type":"type1","imgClass":"look-s1","imgurl":"../../images/img/looks/girl/right/ic_slide_1.png"},
      {"type":"type2","imgClass":"look-s2","imgurl":"../../images/img/looks/girl/right/ic_slide_2.png"},
      {"type":"type3","imgClass":"look-s3","imgurl":"../../images/img/looks/girl/right/ic_slide_3.png"},
      {"type":"type4","imgClass":"look-s3","imgurl":"../../images/img/looks/girl/right/ic_slide_4.png"},
      {"type":"type5","imgClass":"look-s4","imgurl":"../../images/img/looks/girl/right/ic_slide_5.png"},
      {"type":"type6","imgClass":"look-s5","imgurl":"../../images/img/looks/girl/right/ic_slide_6.png"},
      {"type":"type7","imgClass":"look-s7","imgurl":"../../images/img/looks/girl/right/ic_slide_7.png"},
      {"type":"type8","imgClass":"look-s2","imgurl":"../../images/img/looks/girl/right/ic_slide_8.png"},
      {"type":"type9","imgClass":"look-s6","imgurl":"../../images/img/looks/girl/right/ic_slide_9.png"}
	],
	"type1":[//Í··¢
		{"itemView":"itemview1","imgBfStyle":"imgBfStyle1","type":"1","url":"../../images/img/looks/girl/types/2/ic_toufa_1.png"},
		{"itemView":"itemview1","imgBfStyle":"imgBfStyle1","type":"1","url":"../../images/img/looks/girl/types/2/ic_toufa_2.png"},
		{"itemView":"itemview1","imgBfStyle":"imgBfStyle1","type":"1","url":"../../images/img/looks/girl/types/2/ic_toufa_3.png"}
	],
	"type2":[
		{"itemView":"itemview2","imgBfStyle":"imgBfStyle2","type":"2","url":"../../images/img/looks/girl/types/1/ic_shangyi_1.png"},
		{"itemView":"itemview2","imgBfStyle":"imgBfStyle2","type":"2","url":"../../images/img/looks/girl/types/1/ic_shangyi_2.png"},
		{"itemView":"itemview2","imgBfStyle":"imgBfStyle2","type":"2","url":"../../images/img/looks/girl/types/1/ic_shangyi_3.png"},
		{"itemView":"itemview2","imgBfStyle":"imgBfStyle2","type":"2","url":"../../images/img/looks/girl/types/1/ic_shangyi_4.png"},
		{"itemView":"itemview2","imgBfStyle":"imgBfStyle2","type":"2","url":"../../images/img/looks/girl/types/1/ic_shangyi_5.png"},
		{"itemView":"itemview2","imgBfStyle":"imgBfStyle2","type":"2","url":"../../images/img/looks/girl/types/1/ic_shangyi_6.png"},
		{"itemView":"itemview2","imgBfStyle":"imgBfStyle2","type":"2","url":"../../images/img/looks/girl/types/1/ic_shangyi_7.png"}
	],
	"type3":[
		{"itemView":"itemview3","imgBfStyle":"imgBfStyle3","type":"3","url":"../../images/img/looks/girl/types/3/ic_kuzi_1.png"},
		{"itemView":"itemview3","imgBfStyle":"imgBfStyle3","type":"3","url":"../../images/img/looks/girl/types/3/ic_kuzi_2.png"},
		{"itemView":"itemview3","imgBfStyle":"imgBfStyle3","type":"3","url":"../../images/img/looks/girl/types/3/ic_kuzi_3.png"},
		{"itemView":"itemview3","imgBfStyle":"imgBfStyle3","type":"3","url":"../../images/img/looks/girl/types/3/ic_kuzi_4.png"},
		{"itemView":"itemview3","imgBfStyle":"imgBfStyle3","type":"3","url":"../../images/img/looks/girl/types/3/ic_kuzi_5.png"},
		{"itemView":"itemview3","imgBfStyle":"imgBfStyle3","type":"3","url":"../../images/img/looks/girl/types/3/ic_kuzi_6.png"}
	],
	"type4":[
		{"skirtType":"1","itemView":"itemview3","imgBfStyle":"imgBfStyle4","type":"4","url":"../../images/img/looks/girl/types/4/ic_qunzi_1.png"},
		{"skirtType":"1","itemView":"itemview3","imgBfStyle":"imgBfStyle4","type":"4","url":"../../images/img/looks/girl/types/4/ic_qunzi_2.png"},
		{"skirtType":"2","itemView":"itemview3","imgBfStyle":"imgBfStyle4","type":"4","url":"../../images/img/looks/girl/types/4/ic_qunzi_3.png"},
		{"skirtType":"1","itemView":"itemview3","imgBfStyle":"imgBfStyle4","type":"4","url":"../../images/img/looks/girl/types/4/ic_qunzi_4.png"},
	],
	"type5":[
		{"itemView":"itemview4","imgBfStyle":"imgBfStyle5","type":"5","url":"../../images/img/looks/girl/types/5/ic_xiezi_1.png"},
		{"itemView":"itemview4","imgBfStyle":"imgBfStyle5","type":"5","url":"../../images/img/looks/girl/types/5/ic_xiezi_2.png"},
		{"itemView":"itemview4","imgBfStyle":"imgBfStyle5","type":"5","url":"../../images/img/looks/girl/types/5/ic_xiezi_3.png"},
		{"itemView":"itemview4","imgBfStyle":"imgBfStyle5","type":"5","url":"../../images/img/looks/girl/types/5/ic_xiezi_4.png"},
		{"itemView":"itemview4","imgBfStyle":"imgBfStyle5","type":"5","url":"../../images/img/looks/girl/types/5/ic_xiezi_5.png"},
		{"itemView":"itemview4","imgBfStyle":"imgBfStyle5","type":"5","url":"../../images/img/looks/girl/types/5/ic_xiezi_6.png"},
		{"itemView":"itemview4","imgBfStyle":"imgBfStyle5","type":"5","url":"../../images/img/looks/girl/types/5/ic_xiezi_7.png"},
		{"itemView":"itemview4","imgBfStyle":"imgBfStyle5","type":"5","url":"../../images/img/looks/girl/types/5/ic_xiezi_8.png"},
		{"itemView":"itemview4","imgBfStyle":"imgBfStyle5","type":"5","url":"../../images/img/looks/girl/types/5/ic_xiezi_9.png"},
		{"itemView":"itemview4","imgBfStyle":"imgBfStyle5","type":"5","url":"../../images/img/looks/girl/types/5/ic_xiezi_10.png"}
	],
	"type6":[
		{"itemView":"itemview6","imgBfStyle":"imgBfStyle6","paktype":"1","type":"6","url":"../../images/img/looks/girl/types/6/ic_bao_1_1.png"},
		{"itemView":"itemview6","imgBfStyle":"imgBfStyle6","paktype":"2","type":"6","url":"../../images/img/looks/girl/types/6/ic_bao_2_1.png"},
		{"itemView":"itemview6","imgBfStyle":"imgBfStyle6","paktype":"2","type":"6","url":"../../images/img/looks/girl/types/6/ic_bao_2_2.png"},
		{"itemView":"itemview6","imgBfStyle":"imgBfStyle6","paktype":"2","type":"6","url":"../../images/img/looks/girl/types/6/ic_bao_2_3.png"},
		{"itemView":"itemview6","imgBfStyle":"imgBfStyle6","paktype":"3","type":"6","url":"../../images/img/looks/girl/types/6/ic_bao_3_1.png"},	
		{"itemView":"itemview6","imgBfStyle":"imgBfStyle6","paktype":"3","type":"6","url":"../../images/img/looks/girl/types/6/ic_bao_3_2.png"},	
		{"itemView":"itemview6","imgBfStyle":"imgBfStyle6","paktype":"3","type":"6","url":"../../images/img/looks/girl/types/6/ic_bao_3_3.png"},	
		{"itemView":"itemview6","imgBfStyle":"imgBfStyle6","paktype":"3","type":"6","url":"../../images/img/looks/girl/types/6/ic_bao_3_5.png"},	
		{"itemView":"itemview6","imgBfStyle":"imgBfStyle6","paktype":"3","type":"6","url":"../../images/img/looks/girl/types/6/ic_bao_3_6.png"}		
		],
	"type7":[
		{"itemView":"itemview7","imgBfStyle":"imgBfStyle6","type":"7","url":"../../images/img/looks/girl/types/7/ic_yanjing_1.png"},
		{"itemView":"itemview7","imgBfStyle":"imgBfStyle6","type":"7","url":"../../images/img/looks/girl/types/7/ic_yanjing_2.png"},
		{"itemView":"itemview7","imgBfStyle":"imgBfStyle6","type":"7","url":"../../images/img/looks/girl/types/7/ic_yanjing_3.png"},
		{"itemView":"itemview7","imgBfStyle":"imgBfStyle6","type":"7","url":"../../images/img/looks/girl/types/7/ic_yanjing_4.png"},
		{"itemView":"itemview7","imgBfStyle":"imgBfStyle6","type":"7","url":"../../images/img/looks/girl/types/7/ic_yanjing_5.png"},
		{"itemView":"itemview7","imgBfStyle":"imgBfStyle6","type":"7","url":"../../images/img/looks/girl/types/7/ic_yanjing_6.png"},
		{"itemView":"itemview7","imgBfStyle":"imgBfStyle6","type":"7","url":"../../images/img/looks/girl/types/7/ic_yanjing_7.png"},
		{"itemView":"itemview7","imgBfStyle":"imgBfStyle6","type":"7","url":"../../images/img/looks/girl/types/7/ic_yanjing_8.png"},
		{"itemView":"itemview7","imgBfStyle":"imgBfStyle6","type":"7","url":"../../images/img/looks/girl/types/7/ic_yanjing_9.png"},
		{"itemView":"itemview7","imgBfStyle":"imgBfStyle6","type":"7","url":"../../images/img/looks/girl/types/7/ic_yanjing_10.png"}
	],
	"type8":[
		{"itemView":"itemview7","imgBfStyle":"imgBfStyle6","sstype":"1","type":"8","url":"../../images/img/looks/girl/types/8/ic_erhuan_1.png"},
		{"itemView":"itemview7","imgBfStyle":"imgBfStyle6","sstype":"1","type":"8","url":"../../images/img/looks/girl/types/8/ic_erhuan_2.png"},
		{"itemView":"itemview7","imgBfStyle":"imgBfStyle6","sstype":"2","type":"8","url":"../../images/img/looks/girl/types/8/ic_maozi_changfa.png"},
		{"itemView":"itemview7","imgBfStyle":"imgBfStyle6","sstype":"2","type":"8","url":"../../images/img/looks/girl/types/8/ic_maozi_duanfa.png"},
		{"itemView":"itemview7","imgBfStyle":"imgBfStyle6","sstype":"2","type":"8","url":"../../images/img/looks/girl/types/8/ic_maozi_zhongchangfa.png"},
		{"itemView":"itemview7","imgBfStyle":"imgBfStyle6","sstype":"3","type":"8","url":"../../images/img/looks/girl/types/8/ic_shouhuan.png"},
		{"itemView":"itemview7","imgBfStyle":"imgBfStyle6","sstype":"4","type":"8","url":"../../images/img/looks/girl/types/8/ic_xianglian_1.png"},
		{"itemView":"itemview7","imgBfStyle":"imgBfStyle6","sstype":"4","type":"8","url":"../../images/img/looks/girl/types/8/ic_xianglian_2.png"},
		{"itemView":"itemview7","imgBfStyle":"imgBfStyle6","sstype":"4","type":"8","url":"../../images/img/looks/girl/types/8/ic_xianglian_3.png"},
		{"itemView":"itemview7","imgBfStyle":"imgBfStyle6","sstype":"4","type":"8","url":"../../images/img/looks/girl/types/8/ic_xianglian_4.png"},
		{"itemView":"itemview7","imgBfStyle":"imgBfStyle6","sstype":"5","type":"8","url":"../../images/img/looks/girl/types/8/ic_yaodai_1.png"},
		{"itemView":"itemview7","imgBfStyle":"imgBfStyle6","sstype":"5","type":"8","url":"../../images/img/looks/girl/types/8/ic_yaodai_2.png"},

	],
	"type9":[
		{"itemView":"itemview1","imgBfStyle":"imgBfStyle1","type":"9","url":"../../images/img/looks/girl/types/9/ic_slogan_1.png"},
		{"itemView":"itemview1","imgBfStyle":"imgBfStyle1","type":"9","url":"../../images/img/looks/girl/types/9/ic_slogan_2.png"},
		{"itemView":"itemview1","imgBfStyle":"imgBfStyle1","type":"9","url":"../../images/img/looks/girl/types/9/ic_slogan_3.png"},
		{"itemView":"itemview1","imgBfStyle":"imgBfStyle1","type":"9","url":"../../images/img/looks/girl/types/9/ic_slogan_4.png"},
		{"itemView":"itemview1","imgBfStyle":"imgBfStyle1","type":"9","url":"../../images/img/looks/girl/types/9/ic_slogan_5.png"},
		{"itemView":"itemview1","imgBfStyle":"imgBfStyle1","type":"9","url":"../../images/img/looks/girl/types/9/ic_slogan_6.png"},
		{"itemView":"itemview1","imgBfStyle":"imgBfStyle1","type":"9","url":"../../images/img/looks/girl/types/9/ic_slogan_7.png"},
		{"itemView":"itemview1","imgBfStyle":"imgBfStyle1","type":"9","url":"../../images/img/looks/girl/types/9/ic_slogan_8.png"},
	],
}
var boySetting = {
	"right":[
      {"type":"type1","imgClass":"look-s1","imgurl":"../../images/img/looks/boy/right/ic_slide_1.png"},
      {"type":"type2","imgClass":"look-s2","imgurl":"../../images/img/looks/boy/right/ic_slide_2.png"},
      {"type":"type3","imgClass":"look-s3","imgurl":"../../images/img/looks/boy/right/ic_slide_3.png"},
      {"type":"type4","imgClass":"look-s3","imgurl":"../../images/img/looks/boy/right/ic_slide_4.png"},
      {"type":"type5","imgClass":"look-s4","imgurl":"../../images/img/looks/boy/right/ic_slide_5.png"},
      {"type":"type6","imgClass":"look-s5","imgurl":"../../images/img/looks/boy/right/ic_slide_6.png"},
      {"type":"type7","imgClass":"look-s7","imgurl":"../../images/img/looks/boy/right/ic_slide_7.png"},
      {"type":"type8","imgClass":"look-s2","imgurl":"../../images/img/looks/boy/right/ic_slide_8.png"},
      {"type":"type9","imgClass":"look-s6","imgurl":"../../images/img/looks/boy/right/ic_slide_9.png"}
	],
	"type1":[//Í··¢
		{"itemView":"itemview1","imgBfStyle":"imgBfStyle1","type":"1","url":"../../images/img/looks/boy/types/2/ic_toufa_1.png"},
		{"itemView":"itemview1","imgBfStyle":"imgBfStyle1","type":"1","url":"../../images/img/looks/boy/types/2/ic_toufa_2.png"},
		{"itemView":"itemview1","imgBfStyle":"imgBfStyle1","type":"1","url":"../../images/img/looks/boy/types/2/ic_toufa_3.png"}
	],
	"type2":[
		{"itemView":"itemview2","imgBfStyle":"imgBfStyle2","type":"2","url":"../../images/img/looks/boy/types/1/ic_shangyi_1.png"},
		{"itemView":"itemview2","imgBfStyle":"imgBfStyle2","type":"2","url":"../../images/img/looks/boy/types/1/ic_shangyi_2.png"},
		{"itemView":"itemview2","imgBfStyle":"imgBfStyle2","type":"2","url":"../../images/img/looks/boy/types/1/ic_shangyi_3.png"},
		{"itemView":"itemview2","imgBfStyle":"imgBfStyle2","type":"2","url":"../../images/img/looks/boy/types/1/ic_shangyi_4.png"},
		{"itemView":"itemview2","imgBfStyle":"imgBfStyle2","type":"2","url":"../../images/img/looks/boy/types/1/ic_shangyi_5.png"},
		{"itemView":"itemview2","imgBfStyle":"imgBfStyle2","type":"2","url":"../../images/img/looks/boy/types/1/ic_shangyi_6.png"},
		{"itemView":"itemview2","imgBfStyle":"imgBfStyle2","type":"2","url":"../../images/img/looks/boy/types/1/ic_shangyi_7.png"}
	],
	"type3":[
		{"itemView":"itemview3","imgBfStyle":"imgBfStyle3","type":"3","url":"../../images/img/looks/boy/types/3/ic_kuzi_1.png"},
		{"itemView":"itemview3","imgBfStyle":"imgBfStyle3","type":"3","url":"../../images/img/looks/boy/types/3/ic_kuzi_2.png"},
		{"itemView":"itemview3","imgBfStyle":"imgBfStyle3","type":"3","url":"../../images/img/looks/boy/types/3/ic_kuzi_3.png"},
		{"itemView":"itemview3","imgBfStyle":"imgBfStyle3","type":"3","url":"../../images/img/looks/boy/types/3/ic_kuzi_4.png"},
		{"itemView":"itemview3","imgBfStyle":"imgBfStyle3","type":"3","url":"../../images/img/looks/boy/types/3/ic_kuzi_5.png"},
		{"itemView":"itemview3","imgBfStyle":"imgBfStyle3","type":"3","url":"../../images/img/looks/boy/types/3/ic_kuzi_6.png"},
		{"itemView":"itemview3","imgBfStyle":"imgBfStyle3","type":"3","url":"../../images/img/looks/boy/types/3/ic_kuzi_7.png"}
	],
	"type4":[
		{"skirtType":"1","itemView":"itemview3","imgBfStyle":"imgBfStyle4","type":"4","url":"../../images/img/looks/boy/types/4/ic_taozhuang_1.png"},
		{"skirtType":"1","itemView":"itemview3","imgBfStyle":"imgBfStyle4","type":"4","url":"../../images/img/looks/boy/types/4/ic_taozhuang_2.png"}
	],
	"type5":[
		{"itemView":"itemview4","imgBfStyle":"imgBfStyle5","type":"5","url":"../../images/img/looks/boy/types/5/ic_xiezi_1.png"},
		{"itemView":"itemview4","imgBfStyle":"imgBfStyle5","type":"5","url":"../../images/img/looks/boy/types/5/ic_xiezi_2.png"},
		{"itemView":"itemview4","imgBfStyle":"imgBfStyle5","type":"5","url":"../../images/img/looks/boy/types/5/ic_xiezi_3.png"},
		{"itemView":"itemview4","imgBfStyle":"imgBfStyle5","type":"5","url":"../../images/img/looks/boy/types/5/ic_xiezi_4.png"},
		{"itemView":"itemview4","imgBfStyle":"imgBfStyle5","type":"5","url":"../../images/img/looks/boy/types/5/ic_xiezi_5.png"},
		{"itemView":"itemview4","imgBfStyle":"imgBfStyle5","type":"5","url":"../../images/img/looks/boy/types/5/ic_xiezi_6.png"},
		{"itemView":"itemview4","imgBfStyle":"imgBfStyle5","type":"5","url":"../../images/img/looks/boy/types/5/ic_xiezi_7.png"},
		{"itemView":"itemview4","imgBfStyle":"imgBfStyle5","type":"5","url":"../../images/img/looks/boy/types/5/ic_xiezi_8.png"},
		{"itemView":"itemview4","imgBfStyle":"imgBfStyle5","type":"5","url":"../../images/img/looks/boy/types/5/ic_xiezi_9.png"}
	],
	"type6":[
		{"itemView":"itemview6","imgBfStyle":"imgBfStyle6","paktype":"4","type":"6","url":"../../images/img/looks/boy/types/6/ic_bao_1_1.png"},
		{"itemView":"itemview6","imgBfStyle":"imgBfStyle6","paktype":"4","type":"6","url":"../../images/img/looks/boy/types/6/ic_bao_1_2.png"},
		{"itemView":"itemview6","imgBfStyle":"imgBfStyle6","paktype":"4","type":"6","url":"../../images/img/looks/boy/types/6/ic_bao_1_3.png"},
		{"itemView":"itemview6","imgBfStyle":"imgBfStyle6","paktype":"4","type":"6","url":"../../images/img/looks/boy/types/6/ic_bao_1_4.png"},
		{"itemView":"itemview6","imgBfStyle":"imgBfStyle6","paktype":"4","type":"6","url":"../../images/img/looks/boy/types/6/ic_bao_1_5.png"},	
		{"itemView":"itemview6","imgBfStyle":"imgBfStyle6","paktype":"4","type":"6","url":"../../images/img/looks/boy/types/6/ic_bao_1_6.png"},	
		{"itemView":"itemview6","imgBfStyle":"imgBfStyle6","paktype":"2","type":"6","url":"../../images/img/looks/boy/types/6/ic_bao_2_1.png"},	
		{"itemView":"itemview6","imgBfStyle":"imgBfStyle6","paktype":"2","type":"6","url":"../../images/img/looks/boy/types/6/ic_bao_2_2.png"},	
		{"itemView":"itemview6","imgBfStyle":"imgBfStyle6","paktype":"2","type":"6","url":"../../images/img/looks/boy/types/6/ic_bao_2_3.png"}		
	],
	"type7":[],
	"type8":[],
	"type9":[],
}
module.exports = {
	girlSetting:girlSetting,
	boySetting:boySetting
}